### PR TITLE
Replace lorem ipsum text in collections pages

### PR DESCRIPTION
**Pull request by fstrr**
1. Text generated with ChatGPT
2. Each section (e.g., glass, containers, music, etc.) has a specific Education Level, taken from [3.1.5 Reading Level](https://www.w3.org/WAI/WCAG22/Understanding/reading-level.html)
3. The education level is specified in the metadata section on each page

### CODE REVIEW

**Comment by kfranqueiro** [comment]
It looks like the `home` category/exhibits still have lorem ipsum text.

**Comment by fstrr** [comment]
The irony of misspelling "education"…

**Review by rachaelbradley — APPROVED** [review]
Love the wall of woe!

**Comment by kfranqueiro** [comment]
I noticed a few more things still having lorem ipsum text: take a look at the right-hand column of `/fixable/museum/blog/`. The files involved are under `content/blog/in-the-news/`.

**Pull request merged**
