### PR TITLE
Add custom cursor to carousel

### PR DESCRIPTION
**Pull request by kfranqueiro**
Since this came up a couple of times, here's an attempt at making an annoyingly low-contrast cursor over the carousel on the home page.

Not sure whether we want to include this or not, but it's here if we want it.

### CODE REVIEW

**Comment by fstrr** [comment]
It feels a little too low contrast to me. What about doing something like making the cursor a capital letter M from the museum typeface?

**Comment by kfranqueiro** [comment]
Would that no longer fail anything?

**Comment by fstrr** [comment]
good point.

**Review by fstrr — APPROVED** [review]
approving to get this done. I'd like to revisit this in the future to see if we can get something that's a little less blurry.

**Comment by kfranqueiro** [comment]
This idea was roughly based on a site we saw when looking at other sites for inspiration, which had a sort of spotlight effect on a large banner - so the "fuzziness" is intentional. I did say we can take it or leave it though, 'cause I don't know if we want this at all.

cc @rachaelbradley RE whether we want to merge this or just close it.

**Pull request merged**
